### ISSUE TITLE
Crash when using ReactTrixRTEToolbar with toolbarActions

### ISSUE THREAD

**Issue by Axxxx0n** [abhaynikam/react-trix-rte#24] opened 2021-02-15 15:23 UTC
Because of double peerDependency key in package.json lib crashes when using ReactTrixRTEToolbar with toolbarActions.

https://codesandbox.io/s/sad-leavitt-3s4xq?file=/src/App.js

PR: #23

**Comment by abhaynikam** [comment] 2021-02-17 03:46
Closed by #23

**Comment by alejo4373** [comment] 2021-03-11 06:47
I'm running in to this. Any idea when the fix would make it to npm with a new release?

**Comment by abhaynikam** [comment] 2021-03-11 06:51
@alejo4373 My bad. Releasing the new version now.

**Comment by abhaynikam** [comment] 2021-03-11 07:12
@alejo4373 1.0.11 is released. Could you please help us test if this version fixes the issue? Thanks 😊

**Comment by alejo4373** [comment] 2021-03-24 05:11
Unfortunately this is still an issue. I reproduced it in this [codesandbox](https://codesandbox.io/s/great-forest-pkoqb?file=/src/App.js). I'm using the latest version of `react-trix-rte` and `trix` 😢 . Happy to help where I can.   

cc: @abhaynikam @Axxxx0n

**Comment by abhaynikam** [comment] 2021-03-24 05:18
@alejo4373 I'll take a look at this today. Thanks for building a sandbox to reproduce the issue.

**Comment by alejo4373** [comment] 2021-03-24 06:43
So I played with it for a bit and I think this is a problem with `ramda`. I cloned this repo and I ran the example with `yarn build-examples` after adding the `toolbarActions` prop and I got the same error. Furthermore inspecting what is imported from ramda wiith a simple console.log reveals that `.includes` is not a property of the `R` object. When I manually install the latest version of `ramda` everything worked just fine.

**Comment by abhaynikam** [comment] 2021-03-24 06:46
@alejo4373 Cool. It would be great help if you could raise a patch for it as you are already have found the issue. I'll make sure I update the storybooks examples as well on the deployed site. Thanks 😊

**Comment by alejo4373** [comment] 2021-03-24 06:55
Sure, I'll try to have something tomorrow or before the end of the week. I might have a few questions later on though.

**Comment by alejo4373** [comment] 2021-03-24 07:01
like should ramda be a direct dependency instead of a peer dependency? I'm new to the peer dependency ordeal

**Comment by abhaynikam** [comment] 2021-03-24 09:23
@alejo4373 I think the we should work on removing ramda completely because adding it to dependency increase the bundle size and we do not need Ramda so much. Ramda usage in the lib is very less and can be easily replaced. 

The easy fix for the current issue with toolbar is to replace `R.includes` with `toolbarActions.includes("link")`

**Comment by abhaynikam** [comment] 2021-03-29 17:24
Thanks @alejo4373 for working on this ❤️ . I think this issue is now resolved and we can close it. Please free to test it on 1.0.13 version.

**Closed by abhaynikam** 2021-03-29 17:24 UTC
